name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run ruff
        run: ruff check . --config pyproject.toml
      - name: Run black
        run: black --check . --config pyproject.toml
