name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run ruff
        run: ruff check . --config pyproject.toml

      - name: Run black
        run: black --check . --config pyproject.toml

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install tesseract
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Add repo to PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest -vv || if [ $? -eq 5 ]; then echo "No tests to run — skipping"; else exit $?; fi